name: Publish Scripts
on:
  push:
    branches: 
      - main
    tags:
      - 'v*.*.*'

jobs:
  main:
    runs-on: deployinatorv1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish Scripts
        run: publish-scripts ${{github.workspace}}